// <auto-generated />
using System;
using HetVogeltje.Infrastructuur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HetVogeltje.Infrastructuur.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250823200716_newvillanumbertable")]
    partial class newvillanumbertable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HetVogeltje.Domein.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Villa het Vogeltje, is echt vogeltje",
                            ImagePath = "https://placehold.co/600x400",
                            Name = "Vogeltje Villa",
                            Occupancy = 6,
                            Price = 250.0,
                            Sqft = 1500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zon Villa, is echt zon",
                            ImagePath = "https://placehold.co/600x401",
                            Name = "Zon Villa",
                            Occupancy = 8,
                            Price = 300.0,
                            Sqft = 1800
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ster Villa, is echt ster",
                            ImagePath = "https://placehold.co/600x402",
                            Name = "Ster Villa",
                            Occupancy = 10,
                            Price = 350.0,
                            Sqft = 2000
                        },
                        new
                        {
                            Id = 4,
                            Description = "Maan Villa, is echt maan",
                            ImagePath = "https://placehold.co/600x403",
                            Name = "Maan Villa",
                            Occupancy = 12,
                            Price = 400.0,
                            Sqft = 2200
                        },
                        new
                        {
                            Id = 5,
                            Description = "Budget Villa, voor de minder bedeelden onder ons",
                            ImagePath = "https://placehold.co/600x404",
                            Name = "Budget Villa",
                            Occupancy = 3,
                            Price = 150.0,
                            Sqft = 100
                        });
                });

            modelBuilder.Entity("HetVogeltje.Domein.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialeDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            SpecialeDetails = "nummer 101",
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            SpecialeDetails = "nummer 102",
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 103,
                            SpecialeDetails = "nummer 103",
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 104,
                            SpecialeDetails = "speciale villa nummer 104",
                            VillaId = 4
                        },
                        new
                        {
                            Villa_Number = 105,
                            SpecialeDetails = "105",
                            VillaId = 5
                        });
                });

            modelBuilder.Entity("HetVogeltje.Domein.Entities.VillaNumber", b =>
                {
                    b.HasOne("HetVogeltje.Domein.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
